{
  parserClass="org.intellij.elmlang.elmplugin.parser.ElmParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Elm"
  psiImplClassSuffix="Impl"
  psiPackage="org.intellij.elmlang.elmplugin.psi"
  psiImplPackage="org.intellij.elmlang.elmplugin.psi.impl"

  elementTypeHolderClass="org.intellij.elmlang.elmplugin.psi.ElmTypes"
  elementTypeClass="org.intellij.elmlang.elmplugin.psi.ElmElementType"
  tokenTypeClass="org.intellij.elmlang.elmplugin.psi.ElmTokenType"
}

// docs:
// https://github.com/JetBrains/Grammar-Kit
// https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md

elmFile ::= [moduleDeclaration] item_*

private item_ ::= (declaration|WHITE_SPACE|INDENTATION|COMMENT|NEW_LINE)

moduleDeclaration ::= MODULE IDENTIFIER WHERE

declaration ::= IDENTIFIER