{
  parserClass="com.durkiewicz.elmplugin.parser.ElmParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Elm"
  psiImplClassSuffix="Impl"
  psiPackage="com.durkiewicz.elmplugin.psi"
  psiImplPackage="com.durkiewicz.elmplugin.psi.impl"

  elementTypeHolderClass="com.durkiewicz.elmplugin.psi.ElmTypes"
  elementTypeClass="com.durkiewicz.elmplugin.psi.ElmElementType"
  tokenTypeClass="com.durkiewicz.elmplugin.psi.ElmTokenType"

  psiImplUtilClass="com.durkiewicz.elmplugin.psi.impl.ElmPsiImplUtil"
}

// docs:
// https://github.com/JetBrains/Grammar-Kit
// https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md

elmFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {mixin="com.durkiewicz.elmplugin.psi.impl.ElmNamedElementImpl"
  implements="com.durkiewicz.elmplugin.psi.ElmNamedElement" methods=[getKey getValue getName setName getNameIdentifier getPresentation]}